name: sc-atac-explorer
channels:
  - anaconda
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - h5py=2.10.0
  - matplotlib=3.2.2
  - notebook=6.0.3
  - numpy=1.17.0
  - pip=20.1.1
  - pybedtools=0.8.1
  - pybigwig=0.3.17
  - python=3.6.10
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.9.0
  - umap-learn=0.4.6
  - pip:
    - pandas==0.21.0
    - tqdm==4.48.0

